'use client';
import {useRef} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {Aperture,ArrowUpRight,ArrowRight,Orbit,ScanLine,Target,Activity,WifiOff,FileText} from 'lucide-react';
import type {Frame} from '@/lib/types';
const World=dynamic(()=>import('./OrbitalScene'),{ssr:false});
const steps=[{icon:Orbit,title:'Create the world',body:'Choose orbital, UAV or ground-to-air scenes. Configure motion, camera geometry and repeatable seeds.'},{icon:ScanLine,title:'Find the right signal',body:'Observe a synthetic camera feed. Verify the designated beacon through its temporal signature, even among decoys.'},{icon:Target,title:'Keep it in view',body:'Predict motion, steer the virtual camera and recover visibility after a disturbance or dropout.'},{icon:FileText,title:'Bring back evidence',body:'Inspect measured error, lock retention and timing. Save a run and export JSON, CSV or a performance report.'}];
export default function Landing(){const frameRef=useRef<Frame|null>(null);return <div className="landing">
<header className="landing-nav"><Link className="brand" href="/" aria-label="AXIOM home"><span className="brand-mark"><Aperture size={25}/></span><span>AXIOM<small>VIRTUAL FSOC LABORATORY</small></span></Link><nav aria-label="Landing navigation"><a href="#mission">THE MISSION</a><a href="#workflow">HOW IT WORKS</a><Link href="/lab">ENTER THE LAB <ArrowUpRight size={15}/></Link></nav></header>
<section className="landing-hero"><div className="landing-world" aria-hidden="true"><World frameRef={frameRef} scene="orbital"/></div><div className="landing-shade"/><div className="landing-copy"><span className="landing-kicker"><i/> NAUT IQ / SIH 26169</span><h1>FIND THE LIGHT.<br/><em>HOLD THE LINK.</em></h1><p>A virtual laboratory for the first—and crucial—step of mobile optical communication: finding a moving beacon and keeping it in view.</p><div className="landing-cta"><Link href="/lab" className="primary">LAUNCH THE LAB <ArrowUpRight size={19}/></Link><a href="#workflow" className="landing-secondary">EXPLORE THE WORKFLOW <ArrowRight size={17}/></a></div><span className="landing-scope">SOFTWARE SIMULATION / NO OPTICAL HARDWARE REQUIRED</span></div><div className="landing-orbit-label"><span>01 / LOW EARTH ORBIT</span><b>PRECISION<br/>IN MOTION.</b><small>CONCEPTUAL ENVIRONMENT</small></div><div className="landing-hero-bottom"><span><i/> A SOFTWARE TESTBED FOR COARSE ALIGNMENT</span><a href="#mission">SCROLL TO EXPLORE ↓</a></div></section>
<div className="landing-band"><span><Orbit size={18}/>CONFIGURABLE WORLDS</span><span><ScanLine size={18}/>PIXEL-BASED DETECTION</span><span><WifiOff size={18}/>DISTURBANCE & RECOVERY</span><span><Activity size={18}/>MEASURED TELEMETRY</span></div>
<section className="landing-mission" id="mission"><div><span className="landing-kicker">THE CHALLENGE / POINTING, ACQUISITION & TRACKING</span><h2>A NARROW BEAM.<br/><em>A MOVING TARGET.</em></h2></div><div className="landing-mission-copy"><p>Free-space optical communication depends on precise pointing. Before fine alignment can begin, the remote terminal must be acquired and retained inside the camera’s field of view.</p><p>AXIOM makes that coarse alignment loop visible and testable in software. Change the conditions, challenge the tracker and inspect what actually happened.</p><Link href="/lab">BUILD YOUR FIRST EXPERIMENT <ArrowUpRight size={19}/></Link></div></section>
<section className="landing-workflow" id="workflow"><div className="landing-section-head"><div><span className="landing-kicker">THE WORKFLOW / ONE COMPLETE LOOP</span><h2>ACQUIRE. TRACK. RECOVER.</h2></div><span>WORLD → SENSOR → CONTROL → EVIDENCE</span></div><div className="landing-steps">{steps.map((step,i)=><article key={step.title}><div><span>0{i+1}</span><step.icon size={27}/></div><h3>{step.title}</h3><p>{step.body}</p>{i<3&&<ArrowRight className="step-arrow" size={23}/>}</article>)}</div></section>
<section className="landing-final"><div><span className="landing-kicker">YOUR NEXT STEP / INITIALISE THE MISSION</span><h2>PUT THE LOOP<br/><em>TO THE TEST.</em></h2></div><div><p>Launch an experiment or use the lab’s guided demonstration to walk through acquisition, decoys, disturbances and reacquisition.</p><Link href="/lab" className="primary">ENTER AXIOM <ArrowUpRight size={20}/></Link><small>Working browser baseline. Trained AI and hardware integration are planned.</small></div></section>
<footer className="landing-footer"><span>AXIOM / NAUT IQ</span><span>TEAM 130473 · PS 26169 · SMART AUTOMATION</span><span>BROWSER SIMULATION PROTOTYPE</span></footer>
</div>;}
