'use client';
import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import type { Frame,SceneId } from '@/lib/types';
export default function OrbitalScene({frameRef,scene}:{frameRef:React.RefObject<Frame|null>;scene:SceneId}){
 const host=useRef<HTMLDivElement>(null);const [fallback,setFallback]=useState(false);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{setFallback(true);return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.7));renderer.setClearColor('#05060a',1);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;el.appendChild(renderer.domElement);
 const world=new THREE.Scene();world.fog=new THREE.FogExp2('#05060a',.0015);
 const camera=new THREE.PerspectiveCamera(44,1,.1,500);camera.position.set(17,10,30);camera.lookAt(0,-1,-1);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,-1,-1);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=20;controls.maxDistance=50;controls.maxPolarAngle=Math.PI*.6;controls.minPolarAngle=.5;
 world.add(new THREE.AmbientLight('#7690d7',.48));const sun=new THREE.DirectionalLight('#f5f2dc',4.6);sun.position.set(-28,30,20);world.add(sun);const gold=new THREE.PointLight('#f5e600',24,30);gold.position.set(-6,5,1);world.add(gold);const rim=new THREE.DirectionalLight('#ff2e63',.9);rim.position.set(25,-2,-20);world.add(rim);
 // A local, smooth cartographic texture keeps the overview self-contained and offline.
 const textureCanvas=document.createElement('canvas');textureCanvas.width=2048;textureCanvas.height=1024;const ctx=textureCanvas.getContext('2d')!;
 const ocean=ctx.createLinearGradient(0,0,0,1024);ocean.addColorStop(0,'#173750');ocean.addColorStop(.48,'#12334b');ocean.addColorStop(1,'#061729');ctx.fillStyle=ocean;ctx.fillRect(0,0,2048,1024);
 const continents=[[[.04,.2],[.1,.12],[.18,.15],[.24,.24],[.2,.34],[.15,.39],[.16,.49],[.12,.44],[.08,.33]],[[.18,.48],[.23,.49],[.28,.58],[.25,.7],[.21,.85],[.19,.78],[.17,.61]],[[.44,.27],[.5,.24],[.55,.31],[.58,.4],[.55,.56],[.5,.72],[.46,.59],[.43,.4]],[[.45,.2],[.49,.12],[.58,.14],[.62,.1],[.76,.15],[.88,.25],[.85,.35],[.74,.36],[.7,.46],[.65,.49],[.61,.39],[.54,.33]],[[.77,.61],[.85,.58],[.89,.67],[.86,.73],[.8,.72]],[[.3,.12],[.34,.08],[.37,.16],[.34,.24]],[[.58,.58],[.59,.68],[.575,.72],[.57,.64]]];
 ctx.fillStyle='#52706a';for(const shape of continents){ctx.beginPath();const last=shape[shape.length-1];ctx.moveTo((last[0]+shape[0][0])*1024,(last[1]+shape[0][1])*512);shape.forEach(([x,y],i)=>{const next=shape[(i+1)%shape.length];ctx.quadraticCurveTo(x*2048,y*1024,(x+next[0])*1024,(y+next[1])*512);});ctx.closePath();ctx.fill();}
 let terrainSeed=26169;const terrainRand=()=>{terrainSeed=(terrainSeed*1664525+1013904223)>>>0;return terrainSeed/4294967296;};ctx.globalCompositeOperation='source-atop';ctx.globalAlpha=.12;for(let i=0;i<20000;i++){ctx.fillStyle=i%2?'#adc3a1':'#182b32';ctx.fillRect(terrainRand()*2048,terrainRand()*1024,terrainRand()*5+1,terrainRand()*3+1);}ctx.globalAlpha=1;
 ctx.globalCompositeOperation='source-over';const poles=ctx.createLinearGradient(0,0,0,1024);poles.addColorStop(0,'rgba(224,237,241,.9)');poles.addColorStop(.09,'rgba(224,237,241,0)');poles.addColorStop(.87,'rgba(224,237,241,0)');poles.addColorStop(1,'rgba(224,237,241,.85)');ctx.fillStyle=poles;ctx.fillRect(0,0,2048,1024);
 const texture=new THREE.CanvasTexture(textureCanvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const cloudCanvas=document.createElement('canvas');cloudCanvas.width=1024;cloudCanvas.height=512;const cloudCtx=cloudCanvas.getContext('2d')!;for(let i=0;i<600;i++){const x=terrainRand()*1024,y=terrainRand()*512,r=terrainRand()*35+8;const gradient=cloudCtx.createRadialGradient(x,y,0,x,y,r);gradient.addColorStop(0,'rgba(235,245,255,.28)');gradient.addColorStop(1,'rgba(235,245,255,0)');cloudCtx.fillStyle=gradient;cloudCtx.beginPath();cloudCtx.ellipse(x,y,r,r*.3,terrainRand()*.8,0,Math.PI*2);cloudCtx.fill();}const cloudTexture=new THREE.CanvasTexture(cloudCanvas);cloudTexture.colorSpace=THREE.SRGBColorSpace;

 const earth=new THREE.Mesh(new THREE.SphereGeometry(17,80,64),new THREE.MeshStandardMaterial({map:texture,roughness:.93,metalness:.03}));earth.position.set(0,-17,-11);earth.rotation.set(0,-.7,.18);world.add(earth);const clouds=new THREE.Mesh(new THREE.SphereGeometry(17.08,80,64),new THREE.MeshStandardMaterial({map:cloudTexture,transparent:true,opacity:.5,roughness:1,depthWrite:false}));clouds.position.copy(earth.position);clouds.rotation.copy(earth.rotation);world.add(clouds);
 const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(17.24,64,48),new THREE.ShaderMaterial({vertexShader:'varying vec3 n; varying vec3 p; void main(){n=normalize(normalMatrix*normal); vec4 mv=modelViewMatrix*vec4(position,1.);p=-mv.xyz;gl_Position=projectionMatrix*mv;}',fragmentShader:'varying vec3 n; varying vec3 p; void main(){float f=pow(1.-max(dot(normalize(n),normalize(p)),0.),4.);gl_FragColor=vec4(.22,.48,1.,f*.6);}',transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));atmosphere.position.copy(earth.position);world.add(atmosphere);
 if(scene!=='orbital'){earth.visible=false;clouds.visible=false;atmosphere.visible=false;renderer.setClearColor('#05060a',1);world.fog=new THREE.FogExp2('#152532',.017);const groundGeo=new THREE.PlaneGeometry(180,180,70,70);const gp=groundGeo.attributes.position;for(let i=0;i<gp.count;i++){const x=gp.getX(i),y=gp.getY(i);gp.setZ(i,.5*Math.sin(x*.15)*Math.cos(y*.13)+.2*Math.sin(x*.5));}groundGeo.computeVertexNormals();const ground=new THREE.Mesh(groundGeo,new THREE.MeshStandardMaterial({color:'#101620',roughness:1,metalness:.05}));ground.rotation.x=-Math.PI/2;ground.position.y=-4;world.add(ground);const grid=new THREE.GridHelper(120,30,'#655e25','#202432');grid.position.y=-3.5;world.add(grid);}

 let seed=269;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const stars=new Float32Array(850*3);for(let i=0;i<850;i++){stars[i*3]=(rand()-.5)*220;stars[i*3+1]=rand()*130-25;stars[i*3+2]=-20-rand()*160;}const starCanvas=document.createElement('canvas');starCanvas.width=32;starCanvas.height=32;const starCtx=starCanvas.getContext('2d')!;const starGlow=starCtx.createRadialGradient(16,16,0,16,16,16);starGlow.addColorStop(0,'#ffffff');starGlow.addColorStop(.12,'rgba(255,255,255,.9)');starGlow.addColorStop(1,'rgba(255,255,255,0)');starCtx.fillStyle=starGlow;starCtx.fillRect(0,0,32,32);const starTexture=new THREE.CanvasTexture(starCanvas);const sg=new THREE.BufferGeometry();sg.setAttribute('position',new THREE.BufferAttribute(stars,3));world.add(new THREE.Points(sg,new THREE.PointsMaterial({color:'#a0b0d9',map:starTexture,size:.25,transparent:true,opacity:.75,depthWrite:false,blending:THREE.AdditiveBlending})));
 const points=[];for(let i=0;i<=160;i++){const a=i/160*Math.PI*2;points.push(new THREE.Vector3(Math.cos(a)*13,1.3+Math.sin(a)*1.6,Math.sin(a)*9-3));}world.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:'#f5e600',transparent:true,opacity:.2})));
 function terminal(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(1.15,.7,.85),new THREE.MeshStandardMaterial({color:'#8e9eaa',metalness:.8,roughness:.25}));g.add(body);const foil=new THREE.Mesh(new THREE.BoxGeometry(.4,.76,.89),new THREE.MeshStandardMaterial({color:'#d5b86c',metalness:.7,roughness:.4}));foil.position.x=-.46;g.add(foil);for(const side of [-1,1]){const panel=new THREE.Mesh(new THREE.BoxGeometry(.075,1.2,2.5),new THREE.MeshStandardMaterial({color:'#132b4b',metalness:.55,roughness:.25}));panel.position.z=side*1.95;panel.rotation.x=.3;g.add(panel);for(let i=0;i<6;i++){const strip=new THREE.Mesh(new THREE.BoxGeometry(.08,1.21,.018),new THREE.MeshStandardMaterial({color:'#4c718e',metalness:.3,roughness:.8}));strip.position.set(0,0,side*1.95-1.1+i*.4);strip.rotation.x=.3;g.add(strip);}}const lens=new THREE.Mesh(new THREE.CylinderGeometry(.24,.34,.6,24),new THREE.MeshStandardMaterial({color:'#aabc99',metalness:.8,roughness:.15}));lens.rotation.z=Math.PI/2;lens.position.x=.83;g.add(lens);return g;}
 function drone(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.SphereGeometry(.62,24,16),new THREE.MeshStandardMaterial({color:'#8f9a9b',metalness:.65,roughness:.3})));for(const x of [-1,1])for(const z of [-1,1]){const arm=new THREE.Mesh(new THREE.BoxGeometry(2,.12,.13),new THREE.MeshStandardMaterial({color:'#546671',metalness:.7,roughness:.3}));arm.rotation.y=z*x*Math.PI/4;g.add(arm);const rotor=new THREE.Mesh(new THREE.CylinderGeometry(.62,.62,.035,36),new THREE.MeshStandardMaterial({color:'#0f1e29',transparent:true,opacity:.7,metalness:.7,roughness:.3}));rotor.position.set(x*1.1,.12,z*1.1);g.add(rotor);const hub=new THREE.Mesh(new THREE.CylinderGeometry(.14,.14,.25,20),new THREE.MeshStandardMaterial({color:'#becbca',metalness:.8,roughness:.2}));hub.position.set(x*1.1,.1,z*1.1);g.add(hub);}return g;}
 function cameraTerminal(){const g=new THREE.Group();g.add(new THREE.Mesh(new THREE.BoxGeometry(.9,1.3,.8),new THREE.MeshStandardMaterial({color:'#697b87',metalness:.8,roughness:.25})));const lens=new THREE.Mesh(new THREE.CylinderGeometry(.42,.4,.8,36),new THREE.MeshStandardMaterial({color:'#b7c5bb',metalness:.8,roughness:.12}));lens.rotation.z=Math.PI/2;lens.position.set(.6,.3,0);g.add(lens);const base=new THREE.Mesh(new THREE.BoxGeometry(1.5,.18,1.2),new THREE.MeshStandardMaterial({color:'#435660',metalness:.5,roughness:.4}));base.position.y=-.8;g.add(base);return g;}
 const source=scene==='orbital'?terminal():cameraTerminal();source.scale.setScalar(1.5);source.position.set(-6,1,1);source.rotation.y=.35;world.add(source);const target=scene==='orbital'?terminal():drone();target.scale.setScalar(1.15);target.position.set(6,3,-4);target.rotation.y=Math.PI+.2;world.add(target);
 const beacon=new THREE.Mesh(new THREE.SphereGeometry(.13,16,12),new THREE.MeshBasicMaterial({color:'#ff2e63'}));beacon.position.set(-.9,0,0);target.add(beacon);
 const ring=new THREE.Mesh(new THREE.TorusGeometry(1.1,.013,8,100),new THREE.MeshBasicMaterial({color:'#f5e600',transparent:true,opacity:.75}));world.add(ring);
 const lineGeometry=new THREE.BufferGeometry().setFromPoints([source.position,target.position]);const line=new THREE.Line(lineGeometry,new THREE.LineBasicMaterial({color:'#f5e600',transparent:true,opacity:.75}));world.add(line);
 const trail=new THREE.Line(new THREE.BufferGeometry().setFromPoints(Array.from({length:40},(_,i)=>new THREE.Vector3(3+i*.16,3+Math.sin(i*.13)*.5,-4-i*.075))),new THREE.LineDashedMaterial({color:'#ff2e63',dashSize:.16,gapSize:.18,transparent:true,opacity:.5}));trail.computeLineDistances();world.add(trail);
 const size=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();};const observer=new ResizeObserver(size);observer.observe(el);size();let raf=0;
 const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;function animate(){if(!reducedMotion)clouds.rotation.y+=.00003;const f=frameRef.current;if(f){target.position.set(4+f.target.az*.72,2.4+f.target.el*.55,-4+Math.sin(f.metrics.duration*.15));source.rotation.y=.35+f.camera.az*.06;source.rotation.z=f.camera.el*.04;lineGeometry.setFromPoints([source.position,target.position]);line.material.opacity=f.metrics.visible?.65:.08;ring.material.opacity=f.state==='TRACK'?.85:.2;}ring.position.copy(target.position);ring.lookAt(camera.position);controls.update();renderer.render(world,camera);raf=requestAnimationFrame(animate);}animate();
 return()=>{cancelAnimationFrame(raf);observer.disconnect();controls.dispose();world.traverse(o=>{const m=o as THREE.Mesh;m.geometry?.dispose();if(m.material){for(const mat of Array.isArray(m.material)?m.material:[m.material])mat.dispose();}});texture.dispose();cloudTexture.dispose();starTexture.dispose();renderer.dispose();renderer.domElement.remove();};
 },[frameRef,scene]);
 return <div className="orbital-scene" ref={host} data-scene={scene}>{fallback&&<div className="scene-fallback"><div className="fallback-earth"/><div className="fallback-orbit"/><span className="fallback-satellite">✦</span><p>Orbital overview · Sensor simulation remains active</p></div>}</div>;
}
